# Generated by Django 4.2.2 on 2023-06-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_fooditeams_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(max_length=500, upload_to='chef_details')),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
    ]
